export const travelTimePairs = [
  ["Mitte", "Mitte", 10],
  ["Kreuzberg", "Kreuzberg", 10],
  ["Friedrichshain", "Friedrichshain", 10],
  ["Neukölln", "Neukölln", 10],
  ["Prenzlauer Berg", "Prenzlauer Berg", 10],
  ["Charlottenburg", "Charlottenburg", 10],
  ["Schöneberg", "Schöneberg", 10],
  ["Wilmersdorf", "Wilmersdorf", 10],
  ["Treptow-Köpenick", "Treptow-Köpenick", 10],
  ["Pankow", "Pankow", 10],
  ["Lichtenberg", "Lichtenberg", 10],
  ["Mitte", "Kreuzberg", 12],
  ["Mitte", "Friedrichshain", 15],
  ["Mitte", "Prenzlauer Berg", 12],
  ["Mitte", "Neukölln", 18],
  ["Mitte", "Charlottenburg", 20],
  ["Mitte", "Schöneberg", 15],
  ["Kreuzberg", "Neukölln", 10],
  ["Kreuzberg", "Friedrichshain", 10],
  ["Kreuzberg", "Schöneberg", 12],
  ["Friedrichshain", "Prenzlauer Berg", 10],
  ["Friedrichshain", "Lichtenberg", 12],
  ["Neukölln", "Treptow-Köpenick", 15],
  ["Charlottenburg", "Schöneberg", 12],
  ["Charlottenburg", "Wilmersdorf", 10],
  ["Prenzlauer Berg", "Pankow", 12],
] as const;
